### ISSUE TITLE
Problem when running vue 2.4.1 Cannot read property 'dep'

### ISSUE THREAD

**Issue by Tazer** [dkfbasel/vuex-i18n#26]
I'm getting the following error:

```
<rejected> TypeError: Cannot read property 'dep' of undefined
    at ADD_LOCALE (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex-i18n/dist/vuex-i18n.min.js:40:29)
    at wrappedMutationHandler (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:597:5)
    at commitIterator (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:321:7)
    at Array.forEach (native)
    at /Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:320:11
    at Store._withCommit (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:408:3)
    at Store.commit (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:319:8)
    at Object.boundCommit [as commit] (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:275:19)
    at addLocale (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex-i18n/dist/vuex-i18n.min.js:83:12)
    at wrappedActionHandler (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:604:15) }  reason:  TypeError: Cannot read property 'dep' of undefined
    at ADD_LOCALE (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex-i18n/dist/vuex-i18n.min.js:40:29)
    at wrappedMutationHandler (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:597:5)
    at commitIterator (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:321:7)
    at Array.forEach (native)
    at /Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:320:11
    at Store._withCommit (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:408:3)
    at Store.commit (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:319:8)
    at Object.boundCommit [as commit] (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:275:19)
    at addLocale (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex-i18n/dist/vuex-i18n.min.js:83:12)
    at wrappedActionHandler (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex/dist/vuex.js:604:15)
```

**Comment by tikiatua** [comment]
Hi there,

Thank you for reporting this. I will look into it today. This is probably the same issue as #25.

**Comment by Tazer** [comment]
@tikiatua cool! Thanks. Yeah your probably right! 👍

**Comment by tikiatua** [comment]
Hi @Tazer 

I just pushed a new version (1.4.3) that should fix the issue. It could have to do with the version of vuex that your are using.

**Comment by Tazer** [comment]
Tried it out and not getting the dep error atleast 👍
