### ISSUE TITLE
Error when updating from 1.7 > 1.8  SSR

### ISSUE THREAD

**Issue by Tazer** [dkfbasel/vuex-i18n#45]
```
SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at r (/Users/patrikpotocki/Development/chancehill-vue/node_modules/vue-server-renderer/build.js:8438:16)
error during render : /en/
/Users/patrikpotocki/Development/chancehill-vue/node_modules/vuex-i18n/dist/vuex-i18n.es.js:753
export default index;
^^^^^^
```

So it complains on export default index; (SSR)

**Comment by tikiatua** [comment]
Hi @Tazer,

Could you try to use the file dist/vuex-i18n.umd.js? We switched the default file of the package to the es6 version. This is probably the cause of the error you are seeing.

**Comment by Tazer** [comment]
@tikiatua  I will try todo that, is there any good why  todo that with npm/yarn package.json ? 

Cause my vuex-i18n is just:  "vuex-i18n": "1.8.0", in (package.json)

**Comment by tikiatua** [comment]
It should be possible to specify the path when you actually import the script. 

```
// i.e. instead of 
import vuexI18n from 'vuex-i18n';

// use this
import vuexI18n from 'vuex-i18n/dist/vuex-i18n.umd.js';
```

Alternatively you could edit the package.json file in the directory node_modules/vuex-i18n and set the property "main" to "dist/vuex-i18n.umd.js",
