### ISSUE TITLE
What is the version of your rollup

### ISSUE THREAD

**Issue by zhangqiangoffice** [dkfbasel/vuex-i18n#86]
The version of my rollup is 0.63.5. When I ran "rollup -c" after some modify of "src/vuex-i18n-plugin.js", I got the Error: 
```
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
entry is now input
targets is now output
targets.dest is now output.file

src/index.js → dist/vuex-i18n.es.js, dist/vuex-i18n.cjs.js, dist/vuex-i18n.umd.js...
[!] Error: You must supply output.name for UMD bundles
Error: You must supply output.name for UMD bundles
    at error (/home/quentin/.nvm/versions/node/v8.4.0/lib/node_modules/rollup/dist/rollup.js:3365:15)
    at umd (/home/quentin/.nvm/versions/node/v8.4.0/lib/node_modules/rollup/dist/rollup.js:3635:9)
    at Chunk.render (/home/quentin/.nvm/versions/node/v8.4.0/lib/node_modules/rollup/dist/rollup.js:14794:27)
    at /home/quentin/.nvm/versions/node/v8.4.0/lib/node_modules/rollup/dist/rollup.js:22254:38
    at Array.map (<anonymous>)
    at /home/quentin/.nvm/versions/node/v8.4.0/lib/node_modules/rollup/dist/rollup.js:22252:47
    at <anonymous>
```

**Comment by tikiatua** [comment]
Might well be possible, that the current build options are not for the newest rollup version. Would be good to update the configuration.

**Comment by zhangqiangoffice** [comment]
Yes, updating the configuration is good, and can you add the "rollup" to the "devDependencies" in package.json? That would be better！
